### How to use this example: node src/am-server.js examples/dev1.json
### TODO: Directly support TOML parsing in 'am-server.js'?



# Site base URL
site_hostname = "http://localhost:8080"

# Which domain does this instance represent?
org_domain = "localhost"

# Open to anonymous clients?
is_public_oidc_provider = true

# Limit for peers interacting on-demand without whitelisting
public_peers_limit = 100

# Per-peer users limit
per_peer_users_limit_public = 100       # For public peers
per_peer_users_limit_favored = 1000     # For whitelisted peers




[[users]]
name = "admin"
email = "admin@localhost"
totp_secret = "FT5L2SKQKJGTU5GB4NP67N33EF3FHZX3"





[[named_clients]]
client_id = "memos.nekostein.com"
client_secret = "[redacted]"
redirect_uris = [
    "https://memos.nekostein.com/auth/callback",
    "http://10.0.233.127:5230/auth/callback",
    "http://memos-lan.nekostein.com/auth/callback"
]
response_types = [ "code" ]
grant_types = [ "authorization_code" ]
token_endpoint_auth_method = "client_secret_basic"
